# Generated by Django 2.2.1 on 2019-05-31 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'DOG'), ('CAT', 'CAT'), ('FISH', 'FISH')], max_length=10)),
                ('country_of_origin', models.CharField(choices=[('INDIA', 'IND'), ('US', 'US'), ('CHINA', 'CHN'), ('GERMANY', 'GER')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
