# Generated by Django 2.2.1 on 2019-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='country_of_origin',
            field=models.CharField(choices=[('IND', 'IND'), ('US', 'US'), ('CHN', 'CHN'), ('GER', 'GER')], max_length=10),
        ),
    ]
